apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: oauth-configured-placement
  namespace: acm-policies
placementRef:
  name: all-clusters-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: oauth-configured-policy
    apiGroup: policy.open-cluster-management.io
    kind: Policy
